name: PHPUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Валидация composer.json и composer.lock
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Шаг 3: Кэширование зависимостей Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Шаг 5: Установка PHPUnit локально
      - name: Install PHPUnit globally
        run: composer require --dev phpunit/phpunit --no-update
        # Добавляем PHPUnit как временную dev-зависимость

      - name: Update dependencies with PHPUnit
        run: composer update --prefer-dist --no-progress
        # Обновляем зависимости, чтобы PHPUnit был установлен

      # Шаг 6: Запуск тестов
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml